# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_subscription', '0004_auto_20170209_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_paper',
            field=models.ManyToManyField(related_name='papers_subscribed', to='newspapers.Newspapers', verbose_name='subscribed for'),
        ),
    ]
