# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_subscription', '0005_auto_20170209_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.TextField(default='default'),
        ),
    ]
