# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_subscription', '0006_subscription_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(max_length=8),
        ),
    ]
